import Head from 'next/head';
import Buscador from '../components/Buscador';
import ChatContainer from '../components/ChatContainer';
import { NavBar } from '../components/NavBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Cloud Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container m-auto bg-gray-50'>

        <Buscador/>

        <ChatContainer/>

        <NavBar/>

      </div>

    </>
  );
}
